# Generated by Django 5.0.4 on 2024-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='ismarired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default='2024-04-30'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
