# Generated by Django 5.0.4 on 2024-04-30 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_age_student_ismarired_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
