# Generated by Django 4.2.11 on 2024-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_create_time_student_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(default=180),
        ),
    ]
