# Generated by Django 4.2.11 on 2024-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_height_student_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='class1', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='men', max_length=10),
        ),
    ]
